#ifndef NAISYSDESKTOPUTILS_GLOBAL_H
#define NAISYSDESKTOPUTILS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NAISYSDESKTOPUTILS_LIBRARY)
#  define NAISYSDESKTOPUTILS_EXPORT Q_DECL_EXPORT
#else
#  define NAISYSDESKTOPUTILS_EXPORT Q_DECL_IMPORT
#endif

#endif // NAISYSDESKTOPUTILS_GLOBAL_H
